### ISSUE TITLE
Support between queries

### ISSUE THREAD

**Issue by mackeyja92** [rust-rethinkdb/reql#3]
Any plans for supporting between queries?

Edit: I just realized all the docs and examples are outdated compared to the current state of the repo. I cannot seem to make heads or tails of how to run queries based on my reading of the code. I will pull it down and see if I can figure out how to do the same queries I had with the one on crates.io. That might help me figure out how the current state works a bit and might be able to find between queries.

**Comment by rushmorem** [comment]
> Any plans for supporting between queries?

Yes I plan to support all the ReQL commands.

I'm sorry for the outdated documentation. The library has received a major rewrite since `v0.0.5`. I plan to release `v0.0.6` within the next 2 weeks.

**Comment by mackeyja92** [comment]
That's alright. Looking forward to it!

**Comment by rushmorem** [comment]
I'm sorry I had to postpone releasing `v0.0.6`. Since macros 1.1 are just around the corner, I re-evaluated the design of the driver and saw a huge opportunity to not only improve the maintainability of the driver but also its API. I have been working hard on this for the past week or so. Checkout the [table command](https://github.com/rust-rethinkdb/reql/blob/00be40e024f4885f2e9c2e44e8b0a4bf28b599fa/src/commands/table.rs) for example. The commands are now mostly documentation. [The command itself](https://github.com/rust-rethinkdb/reql/blob/00be40e024f4885f2e9c2e44e8b0a4bf28b599fa/src/commands/table.rs#L49) is now a very simple attribute macro.

Build the documentation and checkout the `db` and `table` commands. They will give you a good idea of what the driver will look like in the near future. That API is not stable though. Right now I'm working on a proof of concept to remove the `opt_arg` command altogether and implementing support for very powerful closure handling.

I'm now targeting the release to coincide with the Rust `v1.15.0` release on 3 March. After that I expect things to start stabilizing towards `v1.0`.

**Comment by rushmorem** [comment]
Version `0.0.6-alpha10` is now usable and it has support for between queries. I still need to work on a couple of things before I release `v0.0.6` (hopefully within the next 24 hours). From now on, any command which takes at least one argument or a closure has to pass in the arguments via the `args` macro. This includes the `between` command. For example,

This `JS` query:-

```js
r.table('marvel').between(10, 20, {rightBound: 'closed'})
```

should be written as:-

```rust
r.table("marvel").between(args!(10, 20, {right_bound: "closed"}))
```

when using [version 0.0.6-alpha10](https://docs.rs/reql/0.0.6-alpha10/reql/struct.Client.html#method.between) and above.
